services:

  stms-fyp:
    container_name: stms-fyp
    build: .
    volumes:
      - ./stms-app:/var/www/html
    ports:
      - 9000:80
    environment:
      PUSHER_APP_ID: 1783908
      PUSHER_APP_KEY: 89262f7eab4890f4c68d
      PUSHER_APP_SECRET: ad21b0d12c0c40e56816
      PUSHER_APP_CLUSTER: eu
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stms-fyp
    ports:
    - 3305:3305
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1